tasks:
  - init: yarn install
  - init: echo "${SPOTIFY_VISUALIZED_ENV}" | base64 -d > .env
  # store env: gp env SPOTIFY_VISUALIZED_ENV="$(base64 -w 0 .env)"

  - command: yarn dev
  - command: yarn test
  - command: yarn storybook
